/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as VerifyEmailRouteImport } from "./routes/verify-email"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthenticatedProfileRouteImport } from "./routes/_authenticated/profile"
import { Route as AuthenticatedMembersRouteImport } from "./routes/_authenticated/members"
import { Route as AuthenticatedRoomsIndexRouteImport } from "./routes/_authenticated/rooms.index"
import { Route as AuthenticatedRoomsSlugRouteImport } from "./routes/_authenticated/rooms.$slug"

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: "/members",
  path: "/members",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsIndexRoute = AuthenticatedRoomsIndexRouteImport.update({
  id: "/rooms/",
  path: "/rooms/",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsSlugRoute = AuthenticatedRoomsSlugRouteImport.update({
  id: "/rooms/$slug",
  path: "/rooms/$slug",
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/members": typeof AuthenticatedMembersRoute
  "/profile": typeof AuthenticatedProfileRoute
  "/rooms/$slug": typeof AuthenticatedRoomsSlugRoute
  "/rooms/": typeof AuthenticatedRoomsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/members": typeof AuthenticatedMembersRoute
  "/profile": typeof AuthenticatedProfileRoute
  "/rooms/$slug": typeof AuthenticatedRoomsSlugRoute
  "/rooms": typeof AuthenticatedRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/login": typeof LoginRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/_authenticated/members": typeof AuthenticatedMembersRoute
  "/_authenticated/profile": typeof AuthenticatedProfileRoute
  "/_authenticated/rooms/$slug": typeof AuthenticatedRoomsSlugRoute
  "/_authenticated/rooms/": typeof AuthenticatedRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/reset-password"
    | "/verify-email"
    | "/members"
    | "/profile"
    | "/rooms/$slug"
    | "/rooms/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/reset-password"
    | "/verify-email"
    | "/members"
    | "/profile"
    | "/rooms/$slug"
    | "/rooms"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/login"
    | "/reset-password"
    | "/verify-email"
    | "/_authenticated/members"
    | "/_authenticated/profile"
    | "/_authenticated/rooms/$slug"
    | "/_authenticated/rooms/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-email": {
      id: "/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/profile": {
      id: "/_authenticated/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/members": {
      id: "/_authenticated/members"
      path: "/members"
      fullPath: "/members"
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/rooms/": {
      id: "/_authenticated/rooms/"
      path: "/rooms"
      fullPath: "/rooms/"
      preLoaderRoute: typeof AuthenticatedRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/rooms/$slug": {
      id: "/_authenticated/rooms/$slug"
      path: "/rooms/$slug"
      fullPath: "/rooms/$slug"
      preLoaderRoute: typeof AuthenticatedRoomsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRoomsSlugRoute: typeof AuthenticatedRoomsSlugRoute
  AuthenticatedRoomsIndexRoute: typeof AuthenticatedRoomsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRoomsSlugRoute: AuthenticatedRoomsSlugRoute,
  AuthenticatedRoomsIndexRoute: AuthenticatedRoomsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
